local coc = {
	CocErrorSign = { fg = C.error, style = "bold" },
	CocWarningSign = { fg = C.warn, style = "bold" },
	CocInfoSign = { fg = C.info, style = "bold" },
	CocHintSign = { fg = C.hint, style = "bold" },
	CocCursorRange = { fg = C.black, bg = C.red },
	CocHighlightText = { bg = C.visual_grey },
	CocHighlightRead = { bg = C.visual_grey },
	CocHighlightWrite = { bg = C.visual_grey },
	CocOutlineName = { fg = C.white },

	CocSemProperty = { fg = C.snow },
	CocSemEnumMember = { fg = C.purple },
	CocSemVariable = { fg = C.white },
	CocSemParameter = { fg = C.white },
	CocSemMacro = { link = "Constant" },
	CocSemComment = { link = "Comment" },
	CocSemFunction = { link = "Function" },
	CocSemMethod = { link = "Function" },
	CocSemType = { link = "Type" },
	CocSemClass = { link = "Type" },
	CocSemTypeParameter = { link = "Type" },
	CocSemEnum = { link = "Type" },
	CocSemDependent = { link = "Type" },
	CocSemConcept = { link = "Type" },
	CocSemNamespace = { fg = C.pink },
	CocSemKeyword = { link = "Keyword" },
	CocSemString = { link = "String" },
	CocSemStruct = { link = "Type" },
	CocSemNumber = { link = "Number" },
	CocSemOperator = { link = "Operator" },
}

return coc
