local highlight = {
	ColorColumn = { bg = C.cursor_grey },
	Conceal = {},
	Cursor = { fg = C.black, bg = C.blue },
	CursorIM = {},
	CursorColumn = { bg = C.cursor_grey },
	CursorLine = { bg = C.cursor_grey },
	Directory = { fg = C.blue },
	DiffAdd = { bg = C.green, fg = C.black },
	DiffChange = { bg = C.yellow, fg = C.black },
	DiffDelete = { bg = C.red, fg = C.black },
	DiffText = { bg = C.black, fg = C.yellow },
	ErrorMsg = { fg = C.error },
	VertSplit = { fg = C.vertsplit },
	Folded = { bg = C.cursor_grey, fg = C.comment_grey },
	FoldColumn = {},
	SignColumn = {},
	IncSearch = { fg = C.yellow, bg = C.comment_grey },
	LineNr = { fg = C.gutter_fg_grey },
	CursorLineNr = { style = "bold" },
	MatchParen = { fg = C.blue, style = "underline" },
	ModeMsg = {},
	MoreMsg = {},
	NonText = { fg = C.special_grey },
	Normal = { fg = C.white, bg = C.black },
	Pmenu = { bg = C.menu_grey },
	PmenuSel = { fg = C.black, bg = C.blue },
	PmenuSbar = { bg = C.special_grey },
	PmenuThumb = { bg = C.white },
	Question = { fg = C.purple },
	Search = { fg = C.black, bg = C.yellow },
	SpecialKey = { fg = C.special_grey },
	SpellBad = { fg = C.red },
	SpellCap = { fg = C.orange },
	SpellLocal = { fg = C.orange },
	SpellRare = { fg = C.orange },
	StatusLine = { fg = C.white, bg = C.cursor_grey },
	StatusLineNC = { fg = C.comment_grey },
	TabLine = { fg = C.comment_grey },
	TabLineFill = {},
	TabLineSel = { fg = C.white },
	Title = { fg = C.green },
	Visual = { fg = C.visual_black, bg = C.visual_grey },
	VisualNOS = { bg = C.visual_grey },
	WarningMsg = { fg = C.yellow },
	WildMenu = { fg = C.black, bg = C.blue }
}

return highlight
